### ISSUE TITLE
Sign-up API request not returning appropriate message 

### ISSUE THREAD

**Issue by shikharvaish28** [project-travel-mate/server#155]
Even though the code has been written for returning the message while doing the sign-up, it's registering the user but not returning the message in any case.

### Steps to reproduce

This issue can be reproduced by sending a POST request from Postman. Once the necessary fields are filled in and the request is sent, the status of the app changes to ```Sending``` until ```Cancel``` is pressed. After ```Cancelling``` the operation, when you try to sign-in using the same credentials, sign-in happens

![screenshot 2019-03-05 at 12 10 05 am](https://user-images.githubusercontent.com/22795943/53754830-19048f80-3edb-11e9-8450-690c61939c52.png)

![screenshot 2019-03-05 at 12 11 32 am](https://user-images.githubusercontent.com/22795943/53754903-46513d80-3edb-11e9-83fa-c4f8864c96c3.png)

**Comment by gutsytechster** [comment]
I would like to work on this issue.

**Comment by shikharvaish28** [comment]
Go ahead @gutsytechster

**Comment by gutsytechster** [comment]
I tried several times with different users to sign-up. Initially, it was taking time to respond and giving error as `[Errno 101] Network is unreachable`. Though after few attempts it started to show message as `"Registration successful. Unable to send a welcome email to user"`.
Since it can't authenticate the `EMAIL_HOST`, it throws the `SMTPException` and fall into the except clause here https://github.com/project-travel-mate/server/blob/master/api/modules/users/views.py#L70
However, this message takes time to appear. My guess would be that we didn't wait for enough time for message to appear. I'll ask you to try this again and wait for a few minutes and the message should appear.

**Comment by shikharvaish28** [comment]
I was able to reproduce what you're saying @gutsytechster 

There's another case wherein the password constraints are not fulfilled because of which sign-up faces the issue, but we don't get the appropriate message. It would be great if you could investigate a bit into it.

**Comment by gutsytechster** [comment]
I tried giving an invalid password but it gives me the response as `Invalid Password`. I am not able to reproduce what you are saying.

**Comment by prabhakar267** [comment]
After testing manually, the issue seems to be in `send_email` method.
For a successful Sign up, `201` response code is sent along with a welcome email to user. And for an unsuccessful sign up, `400` code with the reason is sent.

To fix this, we need to add a check that if the server is running in `debug` mode, do not attempt to send email. This can be done by abstracting the emailing sending part to some common utility and having a check there.
